### ISSUE TITLE
Do Not Include Closing PHP Tag In Example Code

### ISSUE THREAD

**Issue by GrahamCampbell** [dseguy/clearPHP#13]
We shouldn't encourage people to include a closing php by including it in the examples. This is because if someone writes a php class and then puts a new line character after the closing tag, php will send the response - not the desired behaviour at all!

**Comment by jrfnl** [comment]
+1

**Comment by GaryJones** [comment]
+1. Omitting the trailing `?>` is also on PSR-2.

**Comment by DimazzzZ** [comment]
Agree. I also think we shouldn't include opening tag too, because all examples are about php.

**Comment by aleksandrzen** [comment]
[+1](http://php.net/manual/en/language.basic-syntax.phptags.php)

**Comment by 2ndkauboy** [comment]
+1

**Comment by iamawebgeek** [comment]
+1

**Comment by ArnaudLigny** [comment]
:+1: 
PSR-2 : "The closing ?> tag MUST be omitted from files containing only PHP."

**Comment by dseguy** [comment]
I understand the usual practice of leaving the last closing ?> out in PHP code.
I also believe that it makes it more readable in a document like this to close this and make the example "a whole". 
In any case, anyone who wants to write a rule "no-closing-tag" is welcome (with examples, of course).
