### ISSUE TITLE
Mess with code example in Avoid Redefining Properties

### ISSUE THREAD

**Issue by u-mulder** [dseguy/clearPHP#23]
Just before the first code sample we have (https://github.com/dseguy/clearPHP/blob/master/rules/avoid-redefining-properties.md#avoid-redefining-properties)
`Check the code below : $lock is defined in a class`
But there's no `$lock` variable. And nothing about `vehicle` too,

**Comment by u-mulder** [comment]
Also the line 
Abstract an final classes are included in this rule.
should be 
Abstract an**d** final classes are included in this rule.

**Comment by dseguy** [comment]
Thanks for the feedback. I finally decided to withdraw this idea.
