### ISSUE TITLE
duplicate pages in the Performances group?

### ISSUE THREAD

**Issue by ghost** [dseguy/clearPHP#24]
Hello. The page "No Uninitialized Variables" 
https://github.com/dseguy/clearPHP/blob/master/rules/no-uninitialized-variable.md 
is very similar to "No Recalculate" page 
https://github.com/dseguy/clearPHP/blob/master/rules/no-recalculate.md
Probably, copy-paste error?

**Comment by dseguy** [comment]
You're all right. no-recalculate was kept, and no-unitialized-variables was moved to no-undefined-variables.
