### ISSUE TITLE
Error text in Imported collision

### ISSUE THREAD

**Issue by u-mulder** [dseguy/clearPHP#25]
In https://github.com/dseguy/clearPHP/blob/master/rules/imported-collision.md#rule-details block 
last code sample with `$a,$b,$c,$d,$e,$f` is obviously **not considered warnings**

**Comment by aleksandrzen** [comment]
I have created [PR](https://github.com/dseguy/clearPHP/pull/26)

**Comment by dseguy** [comment]
PR merged. Thanks.
