### ISSUE TITLE
avoid-those-slow-functions has some bad replacements

### ISSUE THREAD

**Issue by 2ndkauboy** [dseguy/clearPHP#27]
How should someone e.g. remove `in_array()` with `isset()` when the first function operates on values, while the other could only check for a key. You might advice someone trying to use the `isset()`, but it's not really a possible replacement. Same is true of diff/intersect on arrays.

Replacing `array_walk()` and `array_map()` with a foreach-by-reference could cause some side effects as mentioned in the PHP Pitfalls document you linked to. Although the foreach-by-reference is a lot faster, the usage of the other functions is necessary if you use clean and readable functional programming techniques.

**Comment by aleksandrzen** [comment]
@2ndkauboy, I am totally agree with you.

> usage of the other functions is necessary if you use clean and readable functional programming techniques

Yes, but advises in this rule oriented only for speed improvements.

**Comment by aleksandrzen** [comment]
Anothe moment in this rule, which confused me:

> Rule Details
> Using any of the functions mentioned above will trigger a warning.

Which kind of warning have you meant?

**Comment by dseguy** [comment]
in_array() is indeed not a drop-in replacement for isset() : Let me make that clearer in the doc, but the tip is really this one.

**Comment by regiszanandrea** [comment]
@dseguy still not clear in the doc.
