### ISSUE TITLE
No Sleep - Fine in CLI

### ISSUE THREAD

**Issue by philsturgeon** [dseguy/clearPHP#4]
Maybe mention you don't want to put sleep in web facing code specifically, but it's ok in CLI stuff.

https://github.com/dseguy/clearPHP/blob/master/rules/no-sleep.md

Sleep can be pretty handy in big cron jobs when you're doing batch imports and dont want to utterly flood your database.

**Comment by dseguy** [comment]
Good idea. 

Mention added in the "When not to use it" section and the initial description.

**Comment by dseguy** [comment]
closed with 0eb46ed
