### ISSUE TITLE
Rule copied, but not adjusted

### ISSUE THREAD

**Issue by jrfnl** [dseguy/clearPHP#45]
The [No Unused Property](https://github.com/dseguy/clearPHP/blob/master/rules/no-unused-property.md) rule is clearly copied from the [No Unused Variables](https://github.com/dseguy/clearPHP/blob/master/rules/no-unused-variable.md) rule, but both the text and the examples are still the same.

In other words, the _No Unused Property_ rule is invalid at this moment in time.

**Comment by dseguy** [comment]
Right. Let me fix that.
