### ISSUE TITLE
No Eval 

### ISSUE THREAD

**Issue by philsturgeon** [dseguy/clearPHP#6]
Not entirely sure what the point of this is. 

https://github.com/dseguy/clearPHP/blob/master/rules/no-eval.md#rule-details

It doesn't really explain what is happening, and if its good or bad.

Also you say:

> Such code has to be systematically sanitized before it is used.

It's impossible to sanitize eval from user input securely. 

http://stackoverflow.com/questions/5922762/eval-base64-decode-php-virus

http://stackoverflow.com/a/3697776

Best to just NEVER put user input anywhere near eval.

**Comment by dseguy** [comment]
I think the presentation of the middle block was botched, and hide the 2 main points : no cache for eval, and security problems.  I also made the sentence about sanitization scarier.

**Comment by philsturgeon** [comment]
Cool. Could you link commits to issues so folks can see what changed? :)

**Comment by dseguy** [comment]
I'm about to push, yes.

**Comment by dseguy** [comment]
closed in #45d2559
