### ISSUE TITLE
Always Ha(ve|s) Visibility and Interfaces

### ISSUE THREAD

**Issue by Fleshgrinder** [dseguy/clearPHP#79]
The title in [the document](https://github.com/dseguy/clearPHP/blob/master/rules/always-have-visibility.md) is wrong, however, the rule is missing one important point: _Interfaces_

Members of an interface are [per language specification](https://github.com/php/php-langspec/blob/master/spec/15-interfaces.md#methods) always `public` and any other visibility makes no sense. Hence, requiring the visibility to be defined is redundant and (imho) should actually be avoided for clarity.

**Comment by dseguy** [comment]
Thanks for the has/have fix. 

As for interfaces, I added a section 'When not to use it', for interface methods. 
(imho), I'd keep the 'public' mention, as it is not always obvious if a method is from an interface or not : as such, I prefer to keep it simple, constant and consistent. But I understand your point.

**Comment by Fleshgrinder** [comment]
I specifically talked about interfaces, classes that implement methods from an interface of course have to specify the visibility. Java is a good example on how this should be done.

```php
interface I {
    function f();
}

class C implements I {
    public function f() {}
}
```

**Comment by jrfnl** [comment]
Just my two pennies: for auto-documenting code and consistency, I would always recommend making the visibility of methods in an interface explicit.

**Comment by Fleshgrinder** [comment]
> manual-documenting

Corrected that for you, it is already auto-documented through the language specification, and the mere fact that a fatal error is emitted if you write anything other than `public`. 😉

**Comment by jrfnl** [comment]
> t is already auto-documented through the language specification

For experienced devs: true. For less experienced devs: not so much. I've even met PHP devs with 5+ years experience who've never come across the docs before, so you're presuming knowledge which may well not be there.

**Comment by dseguy** [comment]
@Fleshgrinder : I think I read too fast your initial suggestion. Always visibility for classes's methods. And also for traits.

I'll keep the 'public' recommended for 'interfaces', in the 'when not to use it' section. Personally, I'll probably use your convention.
